name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="env/${{ github.ref_name }}.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve -var-file="env/prod.tfvars"
